spring:
  config:
    import: application-secret.yml
  profiles:
    active: local
  jpa:
    open-in-view: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    trying.cosmos: debug

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    trying.cosmos: debug

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    trying.cosmos: debug
