spring:
  config:
    import: application-secret.yml
  profiles:
    active: local
  jpa:
    open-in-view: true
    properties:
      hibernate:
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    port: 6379

logging:
  level:
    trying.cosmos: debug

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
  redis:
    host: localhost
    port: 6379

logging:
  level:
#    trying.cosmos: debug
    trying.cosmos: trace

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    port: 6379

logging:
  level:
    trying.cosmos: debug
